apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
        - name: meuapp
          image: vinici0s/meuapp:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: meuapp-secrets
